In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd().parent
RAW_DATA_DIR = BASE_DIR / "data" / "raw"

print(RAW_DATA_DIR)

c:\Users\HP\Desktop\northwind-sales-analytics\data\raw

In [3]:
orders = pd.read_csv(RAW_DATA_DIR / "Orders.csv")
order_details = pd.read_csv(RAW_DATA_DIR / "Order Details.csv")
products = pd.read_csv(RAW_DATA_DIR / "Products.csv")
customers = pd.read_csv(RAW_DATA_DIR / "Customers.csv")
employees = pd.read_csv(RAW_DATA_DIR / "Employees.csv")

In [4]:
print("Orders:", orders.shape)
print("Order Details:", order_details.shape)
print("Products:", products.shape)
print("Customers:", customers.shape)
print("Employees:", employees.shape)

Orders: (16282, 14)
Order Details: (609283, 5)
Products: (77, 10)
Customers: (93, 11)
Employees: (9, 18)

In [5]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 16282 entries, 0 to 16281
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         16282 non-null  int64
 1   CustomerID      16282 non-null  str
 2   EmployeeID      16282 non-null  int64
 3   OrderDate       16282 non-null  str
 4   RequiredDate    16282 non-null  str
 5   ShippedDate     16261 non-null  str
 6   ShipVia         16282 non-null  int64
 7   Freight         16282 non-null  float64
 8   ShipName        16282 non-null  str
 9   ShipAddress     16282 non-null  str
 10  ShipCity        16282 non-null  str
 11  ShipRegion      16282 non-null  str
 12  ShipPostalCode  16110 non-null  str
 13  ShipCountry     16282 non-null  str
dtypes: float64(1), int64(3), str(10)
memory usage: 1.7 MB

In [8]:
order_details.info()

<class 'pandas.DataFrame'>
RangeIndex: 609283 entries, 0 to 609282
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   OrderID    609283 non-null  int64
 1   ProductID  609283 non-null  int64
 2   UnitPrice  609283 non-null  float64
 3   Quantity   609283 non-null  int64
 4   Discount   609283 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 23.2 MB

In [10]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    93 non-null     str
 1   CompanyName   93 non-null     str
 2   ContactName   93 non-null     str
 3   ContactTitle  93 non-null     str
 4   Address       91 non-null     str
 5   City          91 non-null     str
 6   Region        91 non-null     str
 7   PostalCode    90 non-null     str
 8   Country       91 non-null     str
 9   Phone         91 non-null     str
 10  Fax           69 non-null     str
dtypes: str(11)
memory usage: 8.1 KB

In [11]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EmployeeID       9 non-null      int64
 1   LastName         9 non-null      str
 2   FirstName        9 non-null      str
 3   Title            9 non-null      str
 4   TitleOfCourtesy  9 non-null      str
 5   BirthDate        9 non-null      str
 6   HireDate         9 non-null      str
 7   Address          9 non-null      str
 8   City             9 non-null      str
 9   Region           9 non-null      str
 10  PostalCode       9 non-null      str
 11  Country          9 non-null      str
 12  HomePhone        9 non-null      str
 13  Extension        9 non-null      int64
 14  Photo            9 non-null      str
 15  Notes            9 non-null      str
 16  ReportsTo        8 non-null      float64
 17  PhotoPath        9 non-null      str
dtypes: float64(1), int64(2), str(15)
memory usage: 1.4 KB

In [12]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ProductID        77 non-null     int64
 1   ProductName      77 non-null     str
 2   SupplierID       77 non-null     int64
 3   CategoryID       77 non-null     int64
 4   QuantityPerUnit  77 non-null     str
 5   UnitPrice        77 non-null     float64
 6   UnitsInStock     77 non-null     int64
 7   UnitsOnOrder     77 non-null     int64
 8   ReorderLevel     77 non-null     int64
 9   Discontinued     77 non-null     int64
dtypes: float64(1), int64(7), str(2)
memory usage: 6.1 KB

In [14]:
orders.select_dtypes(include="object").nunique()

C:\Users\HP\AppData\Local\Temp\ipykernel_8984\2993826569.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  orders.select_dtypes(include="object").nunique()

CustomerID           93
OrderDate         15932
RequiredDate      15905
ShippedDate       15839
ShipName             90
ShipAddress          89
ShipCity             70
ShipRegion            9
ShipPostalCode       83
ShipCountry          21
dtype: int64

In [15]:
order_details["Quantity"] = pd.to_numeric(
    order_details["Quantity"],
    downcast="integer"
)

order_details["ProductID"] = pd.to_numeric(
    order_details["ProductID"],
    downcast="integer"
)

order_details["OrderID"] = pd.to_numeric(
    order_details["OrderID"],
    downcast="integer"
)

In [16]:
orders["OrderDate"] = pd.to_datetime(
    orders["OrderDate"],
    errors="coerce"
)

orders["RequiredDate"] = pd.to_datetime(
    orders["RequiredDate"],
    errors="coerce"
)

orders["ShippedDate"] = pd.to_datetime(
    orders["ShippedDate"],
    errors="coerce"
)

In [18]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 16282 entries, 0 to 16281
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         16282 non-null  int64
 1   CustomerID      16282 non-null  str
 2   EmployeeID      16282 non-null  int64
 3   OrderDate       830 non-null    datetime64[us]
 4   RequiredDate    830 non-null    datetime64[us]
 5   ShippedDate     809 non-null    datetime64[us]
 6   ShipVia         16282 non-null  int64
 7   Freight         16282 non-null  float64
 8   ShipName        16282 non-null  str
 9   ShipAddress     16282 non-null  str
 10  ShipCity        16282 non-null  str
 11  ShipRegion      16282 non-null  str
 12  ShipPostalCode  16110 non-null  str
 13  ShipCountry     16282 non-null  str
dtypes: datetime64[us](3), float64(1), int64(3), str(7)
memory usage: 1.7 MB

In [21]:
sales = orders.merge(
    order_details,
    on="OrderID",
    how="inner"
)

sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry,ProductID,UnitPrice,Quantity,Discount
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,Reims,Western Europe,51100,France,11,14.0,12,0.0
1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,Reims,Western Europe,51100,France,42,9.8,10,0.0
2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,Reims,Western Europe,51100,France,72,34.8,5,0.0
3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,Münster,Western Europe,44087,Germany,14,18.6,9,0.0
4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,Münster,Western Europe,44087,Germany,51,42.4,40,0.0

In [22]:
sales = sales.merge(
    products,
    on="ProductID",
    how="left"
)

sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,...,Discount,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice_y,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,0.0,Queso Cabrales,5,4,1 kg pkg.,21.00,22,30,30,0
1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,0.0,Singaporean Hokkien Fried Mee,20,5,32 - 1 kg pkgs.,14.00,26,0,0,1
2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,0.0,Mozzarella di Giovanni,14,4,24 - 200 g pkgs.,34.80,14,0,0,0
3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,0.0,Tofu,6,7,40 - 100 g pkgs.,23.25,35,0,0,0
4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,0.0,Manjimup Dried Apples,24,7,50 - 300 g pkgs.,53.00,20,0,10,0

In [23]:
sales = sales.merge(
    customers,
    on="CustomerID",
    how="left"
)

sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,...,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695
4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695

In [25]:
sales = sales.merge(
    employees,
    on="EmployeeID",
    how="left"
)

sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,...,City,Region,PostalCode,Country,HomePhone_y,Extension_y,Photo_y,Notes_y,ReportsTo_y,PhotoPath_y
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAA...,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp
1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAA...,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp
2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAA...,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp
3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,London,British Isles,EC2 7JR,UK,(71) 555-7773,428,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAA...,Michael is a graduate of Sussex University (MA...,5.0,http://accweb/emmployees/davolio.bmp
4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,London,British Isles,EC2 7JR,UK,(71) 555-7773,428,/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAA...,Michael is a graduate of Sussex University (MA...,5.0,http://accweb/emmployees/davolio.bmp

In [29]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 609283 entries, 0 to 609282
Data columns (total 71 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   OrderID            609283 non-null  int64
 1   CustomerID         609283 non-null  str
 2   EmployeeID         609283 non-null  int64
 3   OrderDate          2155 non-null    datetime64[us]
 4   RequiredDate       2155 non-null    datetime64[us]
 5   ShippedDate        2082 non-null    datetime64[us]
 6   ShipVia            609283 non-null  int64
 7   Freight            609283 non-null  float64
 8   ShipName           609283 non-null  str
 9   ShipAddress        609283 non-null  str
 10  ShipCity           609283 non-null  str
 11  ShipRegion         609283 non-null  str
 12  ShipPostalCode     603207 non-null  str
 13  ShipCountry        609283 non-null  str
 14  ProductID          609283 non-null  int8
 15  UnitPrice_x        609283 non-null  float64
 16  Quantity           609283 non-null  int16
 17  Discount           609283 non-null  float64
 18  ProductName        609283 non-null  str
 19  SupplierID         609283 non-null  int64
 20  CategoryID         609283 non-null  int64
 21  QuantityPerUnit    609283 non-null  str
 22  UnitPrice_y        609283 non-null  float64
 23  UnitsInStock       609283 non-null  int64
 24  UnitsOnOrder       609283 non-null  int64
 25  ReorderLevel       609283 non-null  int64
 26  Discontinued       609283 non-null  int64
 27  CompanyName        609283 non-null  str
 28  ContactName        609283 non-null  str
 29  ContactTitle       609283 non-null  str
 30  Address_x          596000 non-null  str
 31  City_x             596000 non-null  str
 32  Region_x           596000 non-null  str
 33  PostalCode_x       589558 non-null  str
 34  Country_x          596000 non-null  str
 35  Phone              596000 non-null  str
 36  Fax                445390 non-null  str
 37  LastName_x         609283 non-null  str
 38  FirstName_x        609283 non-null  str
 39  Title_x            609283 non-null  str
 40  TitleOfCourtesy_x  609283 non-null  str
 41  BirthDate_x        609283 non-null  str
 42  HireDate_x         609283 non-null  str
 43  Address_y          609283 non-null  str
 44  City_y             609283 non-null  str
 45  Region_y           609283 non-null  str
 46  PostalCode_y       609283 non-null  str
 47  Country_y          609283 non-null  str
 48  HomePhone_x        609283 non-null  str
 49  Extension_x        609283 non-null  int64
 50  Photo_x            609283 non-null  str
 51  Notes_x            609283 non-null  str
 52  ReportsTo_x        542918 non-null  float64
 53  PhotoPath_x        609283 non-null  str
 54  LastName_y         609283 non-null  str
 55  FirstName_y        609283 non-null  str
 56  Title_y            609283 non-null  str
 57  TitleOfCourtesy_y  609283 non-null  str
 58  BirthDate_y        609283 non-null  str
 59  HireDate_y         609283 non-null  str
 60  Address            609283 non-null  str
 61  City               609283 non-null  str
 62  Region             609283 non-null  str
 63  PostalCode         609283 non-null  str
 64  Country            609283 non-null  str
 65  HomePhone_y        609283 non-null  str
 66  Extension_y        609283 non-null  int64
 67  Photo_y            609283 non-null  str
 68  Notes_y            609283 non-null  str
 69  ReportsTo_y        542918 non-null  float64
 70  PhotoPath_y        609283 non-null  str
dtypes: datetime64[us](3), float64(6), int16(1), int64(11), int8(1), str(49)
memory usage: 322.5 MB

In [39]:
sales['Revenue'] = sales['UnitPrice_x'] * sales['Quantity'] * (1 - sales['Discount'])

In [42]:
customer_sales = (
    sales
    .groupby(["CustomerID", "CompanyName"], as_index=False)
    ["Revenue"]
    .sum()
    .sort_values("Revenue", ascending=False)
)

customer_sales.head(10)

   CustomerID                         CompanyName       Revenue
10      BSBEV                       B's Beverages  6.154115e+06
35      HUNGC          Hungry Coyote Import Store  5.698024e+06
63      RANCH                       Rancho grande  5.559110e+06
30      GOURL                 Gourmet Lanchonetes  5.552310e+06
1       ANATR  Ana Trujillo Emparedados y helados  5.534357e+06
66      RICAR                  Ricardo Adocicados  5.524517e+06
22      FOLIG                   Folies gourmandes  5.505503e+06
44      LETSS                   Let's Stop N Shop  5.462198e+06
45      LILAS                   LILA-Supermercado  5.437438e+06
59      PRINI              Princesa Isabel Vinhos  5.436771e+06

In [47]:
employee_sales = (
    sales
    .groupby(
        ["EmployeeID", "FirstName_x", "LastName_x"],
        as_index=False
    )["Revenue"]
    .sum()
    .sort_values("Revenue", ascending=False)
)

employee_sales.head(10)

   EmployeeID FirstName_x LastName_x       Revenue
3           4    Margaret    Peacock  5.148840e+07
4           5      Steven   Buchanan  5.138646e+07
2           3       Janet  Leverling  5.044557e+07
0           1       Nancy    Davolio  4.965942e+07
6           7      Robert       King  4.965190e+07
7           8       Laura   Callahan  4.928114e+07
5           6     Michael     Suyama  4.913997e+07
8           9        Anne  Dodsworth  4.901968e+07
1           2      Andrew     Fuller  4.831410e+07

In [48]:
sales["Year"] = sales["OrderDate"].dt.year

yearly_sales = (
    sales
    .groupby("Year", as_index=False)["Revenue"]
    .sum()
)

yearly_sales

     Year      Revenue
0  2016.0  208083.9700
1  2017.0  617085.2035
2  2018.0  440623.8660

In [49]:
import sys
from pathlib import Path

BASE_DIR = Path.cwd().parent

sys.path.append(str(BASE_DIR))

from src.data_loader import load_raw_data

RAW_DATA_DIR = BASE_DIR / "data" / "raw"

data = load_raw_data(RAW_DATA_DIR)

orders = data["orders"]
order_details = data["order_details"]
products = data["products"]
customers = data["customers"]
employees = data["employees"]